version: 2

jobs:
  build:
    environment:
        AWS_REGION: us-west-2

    docker:
    - image: circleci/golang:1.10

    working_directory: /go/src/github.com/stelligent/mu

    steps:
      - checkout

      - restore_cache:
          key: v1-go-dep-{{ .Branch }}-{{ checksum "Gopkg.lock" }}

      - run:
          name: Dependencies
          command: make deps

      - run:
          name: Test
          command: make test

      - store_test_results:
          path: test-results

      - save_cache:
          key: v1-go-dep-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
          paths:
            - /go/pkg
            - /go/src/github.com/stelligent/mu/vendor
            - ~/.cache/go-build

      - persist_to_workspace:
          root: .
          paths: .

  release:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/stelligent/mu
    steps:
      - attach_workspace:
          at: /go/src/github.com/stelligent/mu

      # The second key is for the repo homebrew-tap
      - add_ssh_keys:
          fingerprints:
            - "53:1f:d0:6f:24:2a:bf:cb:92:0f:bc:1e:14:6e:1d:72"
            - "35:fc:cc:f6:12:88:e2:56:24:17:09:36:3e:53:e6:68"

      ## In order for deploy to work, you need an environment variable set in CircleCI named "GITHUB_TOKEN" that contains
      ##  a token created from https://github.com/settings/tokens
      ##
      ## Also, an read/write SSH key needs to be created and private key added to circle ci
      ##    as per https://circleci.com/docs/adding-read-write-deployment-key/
      ##
      ## Suggest creating a machine user for the token and ssh key to limit access
      ##
      - deploy:
          name: Deploy
          command: |
            git config --global user.email "cplee+mu@nektos.com"
            git config --global user.name "mu-ci"

            make release
            make formula

      - store_artifacts:
          path: artifacts


workflows:
  version: 2
  build-and-release:
    jobs:
      - build:
          filters:
            tags:
              ignore: /^v[0-9]/
      - release:
          requires:
            - build
          filters:
            tags:
              ignore: /^v[0-9]/
            branches:
              only: 
                - develop
                - master
