version: 2

jobs:
  build:
    machine: true

    ## Don't build when new release tags are pushed
    branches:
      ignore:
        - /^v[0-9]/

    steps:
      - run:
          name: Install Glide
          command: |
            sudo add-apt-repository ppa:masterminds/glide -y
            sudo apt-get update
            sudo apt-get install glide -y

      - run:
          name: Setup Source
          command: |
            mkdir -p /home/circleci/.go_workspace/src/github.com/$CIRCLE_PROJECT_USERNAME
            ln -sf "$(pwd)" /home/circleci/.go_workspace/src/github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
            echo "export APP_PATH=/home/circleci/.go_workspace/src/github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME" >> $BASH_ENV

      - run:
          name: Dependencies
          command: make deps
          working_directory: $APP_PATH

      - run:
          name: Compile
          command: make build
          working_directory: $APP_PATH

      - run:
          name: Test
          command: make test
          working_directory: $APP_PATH


      ## In order for deploy to work, you need an environment variable set in CircleCI named "GITHUB_TOKEN" that contains
      ##  a token created from https://github.com/settings/tokens
      ##
      ## Also, an read/write SSH key needs to be created and private key added to circle ci
      ##    as per https://circleci.com/docs/adding-read-write-deployment-key/
      ##
      ## Suggest creating a machine user for the token and ssh key to limit access
      ##
      - deploy:
          name: Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
              make dev-release
            elif [ "${CIRCLE_BRANCH}" == "master" ]; then
              make release
            fi
          working_directory: $APP_PATH




