version: 0.1

phases:
  install:
    commands:
      - apt-get install -y jq

  build:
    commands:
      - curl -s $(jq -r '.values[]|select(.key=="BASE_URL")|.value' env.json) | grep 'Automation for the People'

artifacts:
  files:
    - mu.yml
