version: 0.1

phases:
  install:
    command:
      - apt-get install -y jq

  build:
    commands:
      - curl -sfo /dev/null $(jq -r '.values[]|select(.key=="BASE_URL")|.value' env.json)

artifacts:
  files:
    - mu.yml
